### ISSUE TITLE
Mobs are not spawning in the survival mode

### ISSUE THREAD

**Issue by TajiBiv** [Terrain2/BetterCreative#2]
Just as the title says. I use the mod just for the command /ddn, but, when I start a new world, the mobs don't spawn at night, just this feature that "leaked" from the creative mode, days go by normaly. I didn't test if the world events would happen normaly.

**Comment by Terrain2** [comment]
I believe the issue is this piece of code, which returns the wrong value (should be false when creative and true otherwise). I will fix this soon

https://github.com/Terrain2/BetterCreative/blob/f9f4adb31ea2e2c4961a061cda18dbe86dd3a8ff/Patches.cs#L148-L153

**Comment by TajiBiv** [comment]
Ok man, thanks for your time. Have a good day
